env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "indent": ["error", 4],
  "require-jsdoc": 0,
  "max-len": ["error", 100],
  "react/react-in-jsx-scope": 0,
  "space-before-function-paren": 0
}
